title: "Extension - *Forming global estimates of self-performance from local confidence*"
description: "A Python replication + extension of Rouault, Dayan & Fleming (2019)"
theme: minima
kramdown:
  math_engine: null